# Helix languages configuration file
[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "node_modules/typescript/lib/"}}

# Formatting is currently done with prettier since biome
# only partially supports astro files
[[language]]
name = "astro"
scope = "source.astro"
auto-format = true
file-types = ["astro"]
injection-regex = "astro"
roots = ["package.json", "astro.config.js"]
indent = { tab-width = 2, unit = "  " }
language-servers = ["astro-ls", "biome"]

# Adding language support with biome
[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "jsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

# HTML emmet language configuration
[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "html"
roots = ["package.json"]
language-servers = ["emmet-lsp"]

# Markdown language configuration
#
# I use ltex-ls to improve my prose, and marksman for
# linking documents. I may not need marksman, since I'm 
# not sure if linking to other documents works as intended.
[[language]]
name = "markdown"
language-servers = [{ name = "ltex-ls"}, { name = "marksman"}]
file-types = ["md", "txt"]
injection-regex = "md"
scope = "text.markdown"
roots = ["package.json"]
formatter = { command = "prettier", args = ['--parser', "markdown"]}
auto-format = true

# This contains words that I know are spelled correctly,
# so ltex-ls doesn't give me a warning
[language-server.ltex-ls.config.ltex.dictionary]
"en-US" = [] 
