# Helix languages configuration file
#
# I assign biome as the formatter for JS(X), TS(X), JSON,
# and Astro. So far, it works much faster than prettier!
[[language]]
name = "astro"
scope = "source.astro"
auto-format = true
formatter = { command = "biome", args = ['lsp-proxy']}
file-types = ["astro"]
injection-regex = "astro"
roots = ["package.json", "astro.config.js"]
indent = { tab-width = 2, unit = "  " }
language-servers = ["astro-ls"]

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "node_modules/typescript/lib/"}}

[[language]]
name = "javascript"
formatter = { command = "biome", args = ['lsp-proxy']}
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "biome", args = ['lsp-proxy']}
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "biome", args = ['lsp-proxy']}
auto-format = true

[[language]]
name = "jsx"
formatter = { command = "biome", args = ['lsp-proxy']}
auto-format = true

[[language]]
name = "json"
formatter = { command = "biome", args = ['lsp-proxy']}
auto-format = true

# HTML emmet language configuration
[[language]]
name = "html"
roots = ["package.json"]
language-servers = ["emmet-lsp"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

# Markdown language configuration
#
# I use ltex-ls to improve my prose, and marksman for
# linking documents. I may not need marksman, since I'm 
# not sure if linking to other documents works as intended.
[[language]]
name = "markdown"
language-servers = [{ name = "ltex-ls"}, { name = "marksman"}]
file-types = ["md", "txt"]
injection-regex = "md"
scope = "text.markdown"
roots = ["package.json"]
formatter = { command = "prettier", args = ['--parser', "markdown"]}
auto-format = true

[language-server.ltex-ls.config.ltex.dictionary]
"en-US" = [] 

# Mdx language configuration
#
# Similar to Markdown configuration, but with MDX specific features
[[language]]
name = "mdx"
language-servers = [{name = "mdx-language-server"}, { name = "ltex-ls"}] #, { name = "marksman"}]
file-types = ["mdx"]
scope = "source.mdx"
injection-regex = "mdx"
roots = ["package.json"]
formatter = { command = "prettier", args = ['--parser', "mdx"]}
auto-format = false

[language-server.mdx-language-server]
command = "mdx-language-server"
args = ["--stdio"]
config = { typescript = { enabled = true, tsdk = "node_modules/typescript/lib/"}}

# Using markdown tree sitter first just to see if I can get it working...
[[grammar]]
name = "mdx"
source = { git = "https://github.com/MDeiml/tree-sitter-markdown", rev = "aaf76797aa8ecd9a5e78e0ec3681941de6c945ee", subpath = "tree-sitter-markdown" }
