[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "node_modules/typescript/lib/"}}

[[language]]
name = "astro"
scope = "source.astro"
formatter = { command = "prettier", args = ["--parser", "astro"] }
auto-format = true
file-types = ["astro"]
injection-regex = "astro" 
roots = ["package.json", "astro.config.js"]
indent = { tab-width = 2, unit = "  " }
language-servers = ["astro-ls"]

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"]}
auto-format = true

# TODO: Add auto-formatting to JS/TS if I'd like

# HTML emmet language configuration
[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "html"
roots = ["package.json"]
language-servers = ["emmet-lsp"]

# Markdown language configuration
#
# I use ltex-ls to improve my prose, and marksman for
# linking documents. I may not need marksman, since I'm 
# not sure if linking to other documents works as intended.
[[language]]
name = "markdown"
language-servers = [{ name = "ltex-ls"}, { name = "marksman"}]
file-types = ["md", "txt"]
injection-regex = "md"
scope = "text.markdown"
roots = ["package.json"]
formatter = { command = "prettier", args = ['--parser', "markdown"]}
auto-format = true

# This contains words that I know are spelled correctly,
# so ltex-ls doesn't give me a warning
# TODO this doesn't actually work, so I need to see what's wrong
[language-server.ltex-ls.config.ltex.dictionary]
"en-US" = ["pnpm"] 
